services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-linguaai}
      - POSTGRES_USER=${POSTGRES_USER:-linguaai_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-LinguaAI1008}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-linguaai_user} -d ${POSTGRES_DB:-linguaai}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "${API_PORT:-2025}:2025"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MODEL=${MODEL:-gemini-2.0-flash}
      - GEMINI_BASE_URL=${GEMINI_BASE_URL}
      - API_PORT=${API_PORT:-8002}
      - DB_HOST=db  # Change from localhost to db (the name of the db service)
      - DB_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-linguaai}
      - POSTGRES_USER=${POSTGRES_USER:-linguaai_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-LinguaAI1008}
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "uvicorn backend.api:app --host 0.0.0.0 --port 2025 --reload"

volumes:
  postgres_data:

