services:
  api:
    build: .
    ports:
      - "${API_PORT:-8001}:8001"
    depends_on:
      - db
    environment:
      - API_KEY=${API_KEY}
      - MODEL=${MODEL:-gemini-2.0-flash}
      - BASE_URL=${BASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_USER=${POSTGRES_USER:-linguaai_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-LinguaAI1008}
      - POSTGRES_DB=${POSTGRES_DB:-linguaai}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SSLMODE=disable
    volumes:
      - .:/code
    restart: unless-stopped
    command: >
      sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8001 --reload"
  redis:
    image: redis:7-alpine
    # Internal-only Redis; do not bind host port to avoid conflicts
    expose:
      - "6379"
    volumes:
      - redis-data:/data
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-linguaai_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-LinguaAI1008}
      - POSTGRES_DB=${POSTGRES_DB:-linguaai}
    # Expose Postgres internally; avoid host port binding conflicts
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data: