version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./schema.sql:/app/schema.sql
      - ./ai_tutor.db:/app/ai_tutor.db
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_BASE_URL=${GEMINI_BASE_URL}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash}
      - DATABASE_PATH=./ai_tutor.db
    env_file:
      - .env
    restart: unless-stopped