services:
  api:
    build: .
    ports:
      - "${API_PORT:-8002}:8002"
    environment:
      - API_KEY=${API_KEY}
      - MODEL=${MODEL:-gemini-2.0-flash}
      - BASE_URL=${BASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - .:/code
    restart: unless-stopped
    command: >
      sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8002 --reload"
  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: