services:
  api:   # Changed from 'web' to 'api'
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./output:/code/output
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - API_PORT=${API_PORT}
    env_file:
      - .env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /code