services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-linguaai}
      - POSTGRES_USER=${POSTGRES_USER:-linguaai_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-LinguaAI1008}  # Remove $ from default value
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-linguaai_user} -d ${POSTGRES_DB:-linguaai}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - API_PORT=${API_PORT:-8000}
      - DB_HOST=db  # This must be 'db' not 'localhost'
      - DB_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-linguaai}
      - POSTGRES_USER=${POSTGRES_USER:-linguaai_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-LinguaAI1008}
    volumes:
      - .:/code  # Mount entire project for development
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "python -m backend.wait-for-db &&
             uvicorn backend.api.app:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: