---
services:
  - type: web
    name: fastapi-backend
    runtime: python
    plan: free         # Use 'starter' or 'standard' for paid tiers
    region: oregon     # Options: oregon, ohio, frankfurt, singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.api.app:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true   # Automatically deploy on git push
